In [41]:
import sys

print(sys.executable)

c:\Users\Dell\Customer-Churn-Prediction-ML\venv\Scripts\python.exe

In [42]:
delay_df = pd.read_csv(
    "../data/processed/delay_processed.csv"
)

print(delay_df.columns.tolist())

['train_id', 'train_name', 'source', 'destination', 'distance_km', 'weather', 'temperature', 'rainfall', 'station_delay', 'previous_delay', 'delay_minutes', 'departure_hour']

In [43]:
delay_df["is_peak_hour"] = delay_df["departure_hour"].apply(
    lambda x: 1 if (7 <= x <= 10 or 17 <= x <= 21) else 0
)

In [44]:
print(delay_df[[
    "departure_hour",
    "is_peak_hour"
]].head(10))

   departure_hour  is_peak_hour
0              10             1
1              21             1
2              19             1
3              14             0
4              21             1
5               7             1
6              12             0
7               8             1
8              11             0
9              14             0

In [45]:
weather_mapping = {
    "Clear": 0,
    "Cloudy": 1,
    "Rain": 2,
    "Heavy Rain": 3,
    "Fog": 4
}

delay_df["weather_encoded"] = delay_df["weather"].map(
    weather_mapping
)

In [46]:
print(
    delay_df[
        ["weather", "weather_encoded"]
    ].head()
)

  weather  weather_encoded
0    Rain                2
1   Clear                0
2  Cloudy                1
3  Cloudy                1
4  Cloudy                1

In [47]:
X_delay = delay_df[
    [
        "distance_km",
        "temperature",
        "rainfall",
        "station_delay",
        "previous_delay",
        "departure_hour",
        "is_peak_hour",
        "weather_encoded"
    ]
]

y_delay = delay_df["delay_minutes"]

In [48]:
print("X shape:", X_delay.shape)
print("y shape:", y_delay.shape)

X_delay.head()

X shape: (5000, 8)
y shape: (5000,)

,distance_km,temperature,rainfall,station_delay,previous_delay,departure_hour,is_peak_hour,weather_encoded
0,350,38,12.48,6.12,15.07,10,1,2
1,539,34,41.98,2.90,4.28,21,1,0
2,646,20,68.80,2.90,21.39,19,1,1
3,419,29,39.61,9.48,13.76,14,0,1
4,469,39,2.51,4.29,16.41,21,1,1

In [49]:
import pandas as pd
import numpy as np

In [50]:
delay_df = pd.read_csv(
    "../data/processed/delay_processed.csv"
)

delay_df.head()

,train_id,train_name,source,destination,distance_km,weather,temperature,rainfall,station_delay,previous_delay,delay_minutes,departure_hour
0,TRN1001,Jan Shatabdi,Guntur,Tirupati,350,Rain,38,12.48,6.12,15.07,28.32,10
1,TRN1002,Garib Rath,Hyderabad,Vijayawada,539,Clear,34,41.98,2.90,4.28,15.53,21
2,TRN1003,Shatabdi Express,Guntur,Tirupati,646,Cloudy,20,68.80,2.90,21.39,17.81,19
3,TRN1004,Krishna Express,Secunderabad,Nizamabad,419,Cloudy,29,39.61,9.48,13.76,16.29,14
4,TRN1005,Rajdhani Express,Nellore,Chennai,469,Cloudy,39,2.51,4.29,16.41,26.34,21

In [51]:
delay_df.columns.tolist()

['train_id',
 'train_name',
 'source',
 'destination',
 'distance_km',
 'weather',
 'temperature',
 'rainfall',
 'station_delay',
 'previous_delay',
 'delay_minutes',
 'departure_hour']

In [52]:
weather_mapping = {
    "Clear": 0,
    "Cloudy": 1,
    "Rain": 2,
    "Heavy Rain": 3,
    "Fog": 4
}

delay_df["weather_encoded"] = delay_df["weather"].map(
    weather_mapping
)

In [53]:
delay_df[
    ["weather", "weather_encoded"]
].head()

  weather  weather_encoded
0    Rain                2
1   Clear                0
2  Cloudy                1
3  Cloudy                1
4  Cloudy                1

In [54]:
delay_df["route"] = (
    delay_df["source"]
    + "_to_"
    + delay_df["destination"]
)

In [55]:
delay_df[
    ["source", "destination", "route"]
].head()

         source destination                      route
0        Guntur    Tirupati         Guntur_to_Tirupati
1     Hyderabad  Vijayawada    Hyderabad_to_Vijayawada
2        Guntur    Tirupati         Guntur_to_Tirupati
3  Secunderabad   Nizamabad  Secunderabad_to_Nizamabad
4       Nellore     Chennai         Nellore_to_Chennai

In [56]:
delay_df["previous_delay_category"] = pd.cut(
    delay_df["previous_delay"],
    bins=[-1, 5, 15, float("inf")],
    labels=["Low", "Medium", "High"]
)

In [57]:
delay_df[
    ["previous_delay", "previous_delay_category"]
].head(10)

   previous_delay previous_delay_category
0           15.07                    High
1            4.28                     Low
2           21.39                    High
3           13.76                  Medium
4           16.41                    High
5            4.78                     Low
6            2.43                     Low
7            4.65                     Low
8            3.48                     Low
9            9.05                  Medium

In [58]:
X_delay = delay_df.drop(
    columns=["delay_minutes"]
)

y_delay = delay_df["delay_minutes"]

In [59]:
print("Features:", X_delay.shape)
print("Target:", y_delay.shape)

Features: (5000, 14)
Target: (5000,)

In [60]:
X_delay = delay_df[
    [
        "distance_km",
        "temperature",
        "rainfall",
        "station_delay",
        "previous_delay",
        "departure_hour",
        "is_peak_hour",
        "weather_encoded"
    ]
]

y_delay = delay_df["delay_minutes"]

KeyError: "['is_peak_hour'] not in index"

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(
    X_delay,
    y_delay,
    test_size=0.2,
    random_state=42
)

In [63]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (4000, 14)
X_test: (1000, 14)
y_train: (4000,)
y_test: (1000,)

In [64]:
passenger_df = pd.read_csv(
    "../data/processed/passenger_processed.csv"
)

passenger_df.head()

,date,station,train_id,hour,day_of_week,holiday,weather,special_event,passenger_count
0,2025-05-20,Visakhapatnam,TRN1500,21,1,0,Clear,0,571
1,2025-06-19,Tirupati,TRN1758,20,3,0,Rain,1,1047
2,2025-11-21,Visakhapatnam,TRN4588,9,4,0,Clear,0,661
3,2025-02-10,Secunderabad,TRN1684,0,0,0,Cloudy,0,313
4,2025-11-28,Guntur,TRN4985,23,4,0,Clear,0,268

In [65]:
passenger_df["is_peak_hour"] = passenger_df["hour"].apply(
    lambda x: 1 if (7 <= x <= 10 or 17 <= x <= 21) else 0
)

In [66]:
passenger_df["is_weekend"] = passenger_df[
    "day_of_week"
].apply(
    lambda x: 1 if x >= 5 else 0
)

In [67]:
passenger_df["weather_encoded"] = passenger_df[
    "weather"
].map(weather_mapping)

In [68]:
X_passenger = passenger_df[
    [
        "hour",
        "day_of_week",
        "holiday",
        "special_event",
        "is_peak_hour",
        "is_weekend",
        "weather_encoded"
    ]
]

y_passenger = passenger_df["passenger_count"]

In [69]:
X_train_passenger, X_test_passenger, y_train_passenger, y_test_passenger = train_test_split(
    X_passenger,
    y_passenger,
    test_size=0.2,
    random_state=42
)

In [70]:
maintenance_df = pd.read_csv(
    "../data/processed/maintenance_processed.csv"
)

maintenance_df.head()

,train_id,engine_temperature,brake_pressure,vibration,wheel_condition,engine_hours,last_service_days,maintenance_count,failure
0,TRN5021,91.33,88.74,3.28,55,6057,67,7,0
1,TRN4020,75.91,93.46,3.34,75,5416,257,11,0
2,TRN5714,87.09,90.08,5.38,96,5831,229,4,0
3,TRN5915,62.02,91.54,4.60,85,4060,137,14,1
4,TRN3186,91.01,87.05,3.15,57,11743,146,9,0

In [71]:
X_maintenance = maintenance_df[
    [
        "engine_temperature",
        "brake_pressure",
        "vibration",
        "wheel_condition",
        "engine_hours",
        "last_service_days",
        "maintenance_count"
    ]
]

y_maintenance = maintenance_df["failure"]

In [72]:
X_train_maintenance, X_test_maintenance, y_train_maintenance, y_test_maintenance = train_test_split(
    X_maintenance,
    y_maintenance,
    test_size=0.2,
    random_state=42,
    stratify=y_maintenance
)

In [73]:
crowd_df = pd.read_csv(
    "../data/processed/crowd_processed.csv"
)

crowd_df.head()

,date,station,hour,day_of_week,holiday,train_frequency,passenger_count,entry_count,exit_count,crowd_level
0,2025-04-15,Kurnool,9,1,0,3,139,106,31,Low
1,2025-06-30,Tirupati,2,0,0,8,667,386,394,Low
2,2025-02-15,Nellore,0,5,0,7,1312,723,664,Medium
3,2025-10-14,Vijayawada,15,1,0,12,1390,1045,461,Medium
4,2025-09-19,Warangal,9,4,0,4,975,395,209,Medium

In [74]:
crowd_df["is_peak_hour"] = crowd_df["hour"].apply(
    lambda x: 1 if (7 <= x <= 10 or 17 <= x <= 21) else 0
)

In [75]:
crowd_df["is_weekend"] = crowd_df[
    "day_of_week"
].apply(
    lambda x: 1 if x >= 5 else 0
)

In [76]:
crowd_mapping = {
    "Low": 0,
    "Medium": 1,
    "High": 2
}

crowd_df["crowd_level_encoded"] = crowd_df[
    "crowd_level"
].map(crowd_mapping)

In [77]:
X_crowd = crowd_df[
    [
        "hour",
        "day_of_week",
        "holiday",
        "train_frequency",
        "passenger_count",
        "entry_count",
        "exit_count",
        "is_peak_hour",
        "is_weekend"
    ]
]

y_crowd = crowd_df["crowd_level_encoded"]

In [78]:
X_train_crowd, X_test_crowd, y_train_crowd, y_test_crowd = train_test_split(
    X_crowd,
    y_crowd,
    test_size=0.2,
    random_state=42,
    stratify=y_crowd
)

In [79]:
delay_df.to_csv(
    "../data/processed/delay_processed.csv",
    index=False
)

In [80]:
passenger_df.to_csv(
    "../data/processed/passenger_processed.csv",
    index=False
)

In [81]:
maintenance_df.to_csv(
    "../data/processed/maintenance_processed.csv",
    index=False
)

In [82]:
crowd_df.to_csv(
    "../data/processed/crowd_processed.csv",
    index=False
)

In [83]:
print("Feature engineering completed successfully!")

Feature engineering completed successfully!